server:
  port: 8082

spring:
  application:
    name: WELCOME_API
  boot:
    admin:
      client:
        url: http://localhost:1111/


  cloud:
    compatibility-verifier:
      enabled : false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

