spring:
  cloud:
    config:
      server:
        git:
          uri: https://username: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@github.com/gauravmukatii/configuration_properties.git
          clone-on-start: true
